export const GET_DETAILS = "GET_DETAILS";
export const GET_DETAILS_SUCCESS = "GET_DETAILS_SUCCESS";
export const GET_DETAILS_FAILURE = "GET_DETAILS_FAILURE";

export const CHECKOUT_EDIT_ITEM ="CHECKOUT_EDIT_ITEM";
export const  CHECKOUT_EDIT_ITEM_SUCCESS=" CHECKOUT_EDIT_ITEM_SUCCESS";